In [3]:
import numpy as np

list1 = [1, 2, 3]
list2 = [[10],[20],[30]]

vector1 = np.array(list1)
vector2 = np.array(list2)

print("Horizontal Vector")
print(vector1)

print("Vertical Vector")
print(vector2)

Horizontal Vector
[1 2 3]
Vertical Vector
[[10]
 [20]
 [30]]


In [5]:

list1 = [1, 2, 3]
list2 = [10,20,30]

vector1 = np.array(list1)
vector2 = np.array(list2)

addition = vector1 + vector2
print("Vector Addition : " + str(addition))

subtraction = vector1 - vector2
print("Vector Subtraction : " + str(subtraction))

multiplication = vector1 * vector2
print("Vector Multiplication : " + str(multiplication))

scalar = 2

scalar_mul = vector1 * scalar
print("Scalar Multiplication : " + str(scalar_mul))

division = vector1 / vector2
print("Vector Division : " + str(division))

Vector Addition : [11 22 33]
Vector Subtraction : [ -9 -18 -27]
Vector Multiplication : [10 40 90]
Scalar Multiplication : [2 4 6]
Vector Division : [0.1 0.1 0.1]


In [6]:
# Dot Product
dot_product = vector1.dot(vector2)
print("Dot Product   : " + str(dot_product))

#Cross Product
cross = np.cross(vector1, vector2)
print(cross)

Dot Product   : 140
[0 0 0]


In [10]:
# Vector norm
from numpy.linalg import norm

arr=np.array([1,3,5])          
l=norm(arr,float('inf'))             

print(l)

5.0


In [11]:
#Vector Projection
u = np.array([1, 2, 3])
v = np.array([5, 6, 2]) 

v_norm = np.sqrt(sum(v**2))	
proj_of_u_on_v = (np.dot(u, v)/v_norm**2)*v

print("Projection of Vector u on Vector v is: ", proj_of_u_on_v)

Projection of Vector u on Vector v is:  [1.76923077 2.12307692 0.70769231]


In [12]:
# Linear Combination of vector
x = np.array([[0, 0, 1],[0, 1, 0],[1, 0, 0]])
y = ([3.65, 1.55, 3.42])

scalars = np.linalg.solve(x, y)
scalars

array([3.42, 1.55, 3.65])

In [15]:
# linearly dependent and independent vectors
import sympy 

matrix = np.array([ [0, 5, 1], [0, 0, 0]])
_, indexes = sympy.Matrix(matrix).T.rref()  # T is for transpose

print(indexes)
print(matrix[indexes,:])

if len(indexes) == 2:
    print("linearly independant")
else:
    print("linearly dependant")

(0,)
[[0 5 1]]
linearly dependant


MATRIX

In [16]:
x = np.array([ [1, 2], [4, 5]])
y = np.array([[7, 8], [9, 10]])

print ("The element wise addition of matrix is : ")
print (np.add(x,y))

print ("The element wise subtraction of matrix is : ")
print (np.subtract(x,y))

print ("The element wise division of matrix is : ")
print (np.divide(x,y))

print ("The element wise multiplication of matrix is : ")
print (np.multiply(x,y))

print ("The element wise square root is : ")
print (np.sqrt(x))

print ("The summation of all matrix element is : ")
print (np.sum(y))

print ("The column wise summation of all matrix is : ")
print (np.sum(y,axis=0))

print ("The transpose of given matrix is : ")
print (x.T)

The element wise addition of matrix is : 
[[ 8 10]
 [13 15]]
The element wise subtraction of matrix is : 
[[-6 -6]
 [-5 -5]]
The element wise division of matrix is : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
The element wise multiplication of matrix is : 
[[ 7 16]
 [36 50]]
The element wise square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of all matrix element is : 
34
The column wise summation of all matrix is : 
[16 18]
The transpose of given matrix is : 
[[1 4]
 [2 5]]


In [25]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("inner:", np.inner(a, b))
print("dot:", np.dot(a, b))

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])

print("a", type(a))
print(a)

print("\nb", type(b))
print(b)

c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6], [8, 9]])

print("\ndot product of two ndarray objects")
print(np.dot(a, b))

print("\ndot product of two matrix objects")
print(np.dot(c, d))
print("inner:", np.inner(c, d))

inner: 32
dot: 32
a <class 'numpy.ndarray'>
[[1 2]
 [3 4]]

b <class 'numpy.ndarray'>
[[ 5  6  7]
 [ 8  9 10]]

dot product of two ndarray objects
[[21 24 27]
 [47 54 61]]

dot product of two matrix objects
[[21 24]
 [47 54]]
inner: [[17 26]
 [39 60]]


In [26]:
c * d

matrix([[21, 24],
        [47, 54]])

In [27]:
## Linear combinations
x = np.matrix([[0,1,1],
               [1,1,0],
               [1,0,1]])
y = ([3.65, 1.55, 3.42])
scalars = np.linalg.solve(x,y)
scalars

array([0.66, 0.89, 2.76])

In [30]:
## Linear dependence and span
import matplotlib.pyplot as plt

x = np.arange(-10, 10)
y = 2 * x + 1

plt.figure()
plt.plot(x, y)
plt.xlim(-10,10)
plt.ylim(-10,10)
plt.axvline(x=0)
plt.axhline(y=0)
plt.show()

In [33]:
x = np.arange(-10,10)
y = 2*x + 1
y1 = 6*x - 2

plt.figure()
plt.plot(x, y)
plt.plot(x, y1)
plt.xlim(-2,10)
plt.ylim(-2,10)
plt.axvline(x=0)
plt.axhline(y=0)
plt.show()

In [34]:
## Trace of a matrix
a = np.matrix([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("Trace : ",a.trace())

Trace :  [[7]]


In [35]:
## Rank of a matrix
a = np.arange(1, 10)
a.shape = (3, 3)

rank = np.linalg.matrix_rank(a)
print("Rank : ",rank)

Rank :  2


In [36]:
## Determinant of a matrix
a = np.matrix([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])
print("Determinant : ",np.linalg.det(a))

Determinant :  4.999999999999999


In [37]:
## True inverse 
## If det of sq matrix is not 0 it has a  true inverse

det = np.linalg.det(a)
if det!= 0:
    inv = np.linalg.inv(a)
    print("True inverse : ",inv)

True inverse :  [[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


In [38]:
## Flatten a martix to a vector

print(a.flatten())

[[2 2 1 1 3 1 1 2 2]]


In [39]:
## Eigen values and vectors
a = np.matrix([[2, 2, 1],
               [1, 3, 1],
               [1, 2, 2]])

w, v = np.linalg.eig(a)

print("Eigen values : ",w)
print("Eigen vectors : ",v)

Eigen values :  [1. 5. 1.]
Eigen vectors :  [[-0.90453403  0.57735027  0.04093652]
 [ 0.30151134  0.57735027 -0.46313831]
 [ 0.30151134  0.57735027  0.88534011]]


Decompositions

In [47]:
## LU decomposition

import numpy as np
from scipy.linalg import lu

A = np.array([[2, 3, 1],
              [4, 1, -3],
              [-2, 4, 1]])

# Perform LU decomposition
P, L, U = lu(A)

print("Matrix A:")
print(A)

print("\nPermutation Matrix P:")
print(P)

print("\nLower Triangular Matrix L:")
print(L)

print("\nUpper Triangular Matrix U:")
print(U)

# Verify that A = P @ L @ U
print("\nCheck: P @ L @ U:")
print(P @ L @ U)


Matrix A:
[[ 2  3  1]
 [ 4  1 -3]
 [-2  4  1]]

Permutation Matrix P:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

Lower Triangular Matrix L:
[[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5         0.55555556  1.        ]]

Upper Triangular Matrix U:
[[ 4.          1.         -3.        ]
 [ 0.          4.5        -0.5       ]
 [ 0.          0.          2.77777778]]

Check: P @ L @ U:
[[ 2.  3.  1.]
 [ 4.  1. -3.]
 [-2.  4.  1.]]


In [52]:
import numpy as np
from scipy.linalg import svd

# Define a matrix
A = np.array([[1, 2], [3, 4], [5, 6]])
print("Matrix A:")
print(A)

# Perform Singular Value Decomposition
U, s, VT = svd(A)

# Print the results
print("\nLeft Singular Vectors (U):")
print(U)

print("\nSingular Values (s):")
print(s)

print("\nRight Singular Vectors Transposed (VT):")
print(VT)


Matrix A:
[[1 2]
 [3 4]
 [5 6]]

Left Singular Vectors (U):
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

Singular Values (s):
[9.52551809 0.51430058]

Right Singular Vectors Transposed (VT):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [53]:
# pinv used to Compute the (Moore-Penrose) pseudo-inverse of a matrix.

A = np.array([[-2, -1], [4, -1], [-1, -1]])
A_plus = np.linalg.pinv(A)
A_plus

array([[-0.11290323,  0.17741935, -0.06451613],
       [-0.37096774, -0.27419355, -0.35483871]])

In [54]:
x1 = np.linspace(-5, 5, 1000)
x2_1 = -2*x1 + 2
x2_2 = 4*x1 + 8
x2_3 = -1*x1 + 2

plt.plot(x1, x2_1)
plt.plot(x1, x2_2)
plt.plot(x1, x2_3)
plt.xlim(-2., 1)
plt.ylim(1, 5)
plt.show()